function daysAgoIso(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

function daysAgo(n) {
  return daysAgoIso(n).split('T')[0]
}
function daysFromNow(n) {
  const d = new Date()
  d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}

/** 15 realistic grad-role applications for local dev seeding */
export function getDevTestApplications() {
  return [
    {
      company_name: 'Google',
      company_domain: 'google.com',
      role: 'Software Engineer, New Grad 2026',
      location: 'hybrid',
      location_place: 'Mountain View, CA',
      status: 'applied',
      applied_date: daysAgo(18),
      salary: '$180,000 + equity',
      job_url: 'https://careers.google.com/jobs/results/123456',
      tags: ['Tech', 'Dream Company'],
      notes: 'Referral from alumni mentor. OA completed — waiting on team match.',
    },
    {
      company_name: 'Goldman Sachs',
      company_domain: 'goldmansachs.com',
      role: 'Technology Analyst Program',
      location: 'on-site',
      location_place: 'New York, NY',
      status: 'interviewing',
      applied_date: daysAgo(25),
      salary: '$110,000 base',
      job_url: 'https://goldmansachs.com/careers/students',
      tags: ['Finance', 'Priority'],
      notes: 'Superday scheduled next week. Practicing market-making case studies.',
    },
    {
      company_name: 'Jane Street',
      company_domain: 'janestreet.com',
      role: 'Software Engineer — New Grad',
      location: 'on-site',
      location_place: 'New York, NY',
      status: 'offer',
      applied_date: daysAgo(30),
      salary: '$200,000 + bonus',
      job_url: 'https://www.janestreet.com/join-jane-street/careers/',
      tags: ['Tech', 'Dream Company', 'Priority'],
      notes: 'Verbal offer received. Decision deadline in 2 weeks.',
    },
    {
      company_name: 'Stripe',
      company_domain: 'stripe.com',
      role: 'Backend Engineer, New Grad',
      location: 'remote',
      location_place: 'Remote (US)',
      status: 'applied',
      applied_date: daysAgo(12),
      salary: '$150,000 + equity',
      job_url: 'https://stripe.com/jobs/listing/backend-engineer-new-grad',
      tags: ['Tech', 'Remote'],
      notes: 'Submitted take-home. Strong fit with payments API coursework.',
    },
    {
      company_name: 'McKinsey & Company',
      company_domain: 'mckinsey.com',
      role: 'Digital Consultant — Graduate',
      location: 'hybrid',
      location_place: 'London, UK',
      status: 'rejected',
      applied_date: daysAgo(45),
      salary: '£60,000',
      job_url: 'https://www.mckinsey.com/careers',
      tags: ['Priority'],
      notes: 'Rejected after final round. Feedback: strengthen structured case frameworks.',
    },
    {
      company_name: 'Palantir',
      company_domain: 'palantir.com',
      role: 'Forward Deployed Engineer',
      location: 'on-site',
      location_place: 'Denver, CO',
      status: 'interviewing',
      applied_date: daysAgo(20),
      salary: '$135,000 + equity',
      job_url: 'https://jobs.lever.co/palantir',
      tags: ['Tech'],
      notes: 'On-site decomposition interview next Tuesday.',
    },
    {
      company_name: 'Bloomberg',
      company_domain: 'bloomberg.com',
      role: 'Software Engineer — Graduate Programme',
      location: 'hybrid',
      location_place: 'New York, NY',
      status: 'applied',
      applied_date: daysAgo(8),
      salary: '$120,000',
      job_url: 'https://careers.bloomberg.com/job/search',
      tags: ['Finance', 'Tech'],
      notes: 'Applied via campus career fair. HackerRank pending.',
    },
    {
      company_name: 'Netflix',
      company_domain: 'netflix.com',
      role: 'Software Engineer L4 — New Grad',
      location: 'remote',
      location_place: 'Remote (US)',
      status: 'rejected',
      applied_date: daysAgo(35),
      salary: '$170,000',
      job_url: 'https://jobs.netflix.com/jobs/search',
      tags: ['Tech', 'Dream Company'],
      notes: 'No response after 3 weeks — assumed rejected.',
    },
    {
      company_name: 'Two Sigma',
      company_domain: 'twosigma.com',
      role: 'Quantitative Software Engineer — Campus',
      location: 'on-site',
      location_place: 'New York, NY',
      status: 'applied',
      applied_date: daysAgo(14),
      salary: '$180,000 + bonus',
      job_url: 'https://careers.twosigma.com/careers/OpenRoles',
      tags: ['Finance', 'Priority'],
      notes: 'Phone screen completed. Awaiting technical round invite.',
    },
    {
      company_name: 'Amazon',
      company_domain: 'amazon.com',
      role: 'SDE I — New Grad 2026',
      location: 'hybrid',
      location_place: 'Seattle, WA',
      status: 'saved',
      deadline: daysFromNow(5),
      saved_date: daysAgoIso(3),
      salary: '$115,000 + sign-on',
      job_url: 'https://amazon.jobs/en/jobs/2345678',
      tags: ['Tech'],
      saved_notes: 'Need to tailor resume for AWS experience. Apply before deadline.',
    },
    {
      company_name: 'Microsoft',
      company_domain: 'microsoft.com',
      role: 'Software Engineer — Full-Time New Grad',
      location: 'hybrid',
      location_place: 'Redmond, WA',
      status: 'applied',
      applied_date: daysAgo(22),
      salary: '$130,000 + stock',
      job_url: 'https://careers.microsoft.com/students',
      tags: ['Tech'],
      notes: 'Applied to Azure team. Recruiter reached out on LinkedIn.',
    },
    {
      company_name: 'Meta',
      company_domain: 'meta.com',
      role: 'Software Engineer E3 — New Grad',
      location: 'hybrid',
      location_place: 'Menlo Park, CA',
      status: 'rejected',
      applied_date: daysAgo(40),
      salary: '$160,000 + RSUs',
      job_url: 'https://www.metacareers.com/jobs/',
      tags: ['Tech'],
      notes: 'Failed coding round — need more graph practice.',
    },
    {
      company_name: 'Citadel',
      company_domain: 'citadel.com',
      role: 'Software Engineer — Campus Hire',
      location: 'on-site',
      location_place: 'Chicago, IL',
      status: 'saved',
      deadline: daysFromNow(12),
      saved_date: daysAgoIso(1),
      salary: '$175,000 + bonus',
      job_url: 'https://www.citadel.com/careers/open-roles/',
      tags: ['Finance', 'Dream Company'],
      saved_notes: 'Competitive comp. Finish systems design prep before applying.',
    },
    {
      company_name: 'Deloitte',
      company_domain: 'deloitte.com',
      role: 'Technology Consultant — Graduate Programme',
      location: 'on-site',
      location_place: 'Toronto, ON',
      status: 'applied',
      applied_date: daysAgo(16),
      salary: 'CAD $75,000',
      job_url: 'https://apply.deloitte.com/careers/',
      tags: ['Finance'],
      notes: 'Video interview completed. Case study prep for next round.',
    },
    {
      company_name: 'Spotify',
      company_domain: 'spotify.com',
      role: 'Backend Engineer — Graduate Programme',
      location: 'hybrid',
      location_place: 'Stockholm, Sweden',
      status: 'interviewing',
      applied_date: daysAgo(28),
      deadline: daysFromNow(3),
      salary: '€55,000',
      job_url: 'https://www.lifeatspotify.com/jobs',
      tags: ['Tech', 'Remote'],
      notes: 'Technical interview Friday. Reviewing distributed systems notes.',
    },
  ]
}

export const isDevEnvironment = import.meta.env.DEV
